{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "* Running on local URL:  http://127.0.0.1:7860\n",
      "\n",
      "To create a public link, set `share=True` in `launch()`.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://127.0.0.1:7860/\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\gradio\\route_utils.py\", line 790, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 74, in app\n",
      "    await response(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\responses.py\", line 338, in __call__\n",
      "    await send(\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in _send\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 510, in send\n",
      "    output = self.conn.send(event=h11.EndOfMessage())\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 512, in send\n",
      "    data_list = self.send_with_data_passthrough(event)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 545, in send_with_data_passthrough\n",
      "    writer(event, data_list.append)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 67, in __call__\n",
      "    self.send_eom(event.headers, write)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 96, in send_eom\n",
      "    raise LocalProtocolError(\"Too little data for declared Content-Length\")\n",
      "h11._util.LocalProtocolError: Too little data for declared Content-Length\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 0.988\n",
      "Max probability at index: 13\n",
      "Corresponds to label: minimalism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 23\n",
      "Corresponds to label: surrealism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 13\n",
      "Corresponds to label: minimalism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.043 to 1.000\n",
      "Max probability at index: 13\n",
      "Corresponds to label: minimalism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.059 to 1.000\n",
      "Max probability at index: 13\n",
      "Corresponds to label: minimalism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 0\n",
      "Corresponds to label: abstract_expressionism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 13\n",
      "Corresponds to label: minimalism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 3\n",
      "Corresponds to label: art_informel\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\gradio\\route_utils.py\", line 790, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 74, in app\n",
      "    await response(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\responses.py\", line 338, in __call__\n",
      "    await send(\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in _send\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 510, in send\n",
      "    output = self.conn.send(event=h11.EndOfMessage())\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 512, in send\n",
      "    data_list = self.send_with_data_passthrough(event)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 545, in send_with_data_passthrough\n",
      "    writer(event, data_list.append)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 67, in __call__\n",
      "    self.send_eom(event.headers, write)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 96, in send_eom\n",
      "    raise LocalProtocolError(\"Too little data for declared Content-Length\")\n",
      "h11._util.LocalProtocolError: Too little data for declared Content-Length\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 3\n",
      "Corresponds to label: art_informel\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 19\n",
      "Corresponds to label: pop_art\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 19\n",
      "Corresponds to label: pop_art\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\gradio\\route_utils.py\", line 790, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 74, in app\n",
      "    await response(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\responses.py\", line 338, in __call__\n",
      "    await send(\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in _send\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 510, in send\n",
      "    output = self.conn.send(event=h11.EndOfMessage())\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 512, in send\n",
      "    data_list = self.send_with_data_passthrough(event)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 545, in send_with_data_passthrough\n",
      "    writer(event, data_list.append)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 67, in __call__\n",
      "    self.send_eom(event.headers, write)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 96, in send_eom\n",
      "    raise LocalProtocolError(\"Too little data for declared Content-Length\")\n",
      "h11._util.LocalProtocolError: Too little data for declared Content-Length\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 15\n",
      "Corresponds to label: naive_art\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\gradio\\route_utils.py\", line 790, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 74, in app\n",
      "    await response(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\responses.py\", line 338, in __call__\n",
      "    await send(\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in _send\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 510, in send\n",
      "    output = self.conn.send(event=h11.EndOfMessage())\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 512, in send\n",
      "    data_list = self.send_with_data_passthrough(event)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 545, in send_with_data_passthrough\n",
      "    writer(event, data_list.append)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 67, in __call__\n",
      "    self.send_eom(event.headers, write)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 96, in send_eom\n",
      "    raise LocalProtocolError(\"Too little data for declared Content-Length\")\n",
      "h11._util.LocalProtocolError: Too little data for declared Content-Length\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\gradio\\route_utils.py\", line 790, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 74, in app\n",
      "    await response(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\responses.py\", line 338, in __call__\n",
      "    await send(\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in _send\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 510, in send\n",
      "    output = self.conn.send(event=h11.EndOfMessage())\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 512, in send\n",
      "    data_list = self.send_with_data_passthrough(event)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 545, in send_with_data_passthrough\n",
      "    writer(event, data_list.append)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 67, in __call__\n",
      "    self.send_eom(event.headers, write)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 96, in send_eom\n",
      "    raise LocalProtocolError(\"Too little data for declared Content-Length\")\n",
      "h11._util.LocalProtocolError: Too little data for declared Content-Length\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 406, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\gradio\\route_utils.py\", line 790, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\routing.py\", line 74, in app\n",
      "    await response(scope, receive, send)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\responses.py\", line 338, in __call__\n",
      "    await send(\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\_exception_handler.py\", line 48, in sender\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in _send\n",
      "    await send(message)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 510, in send\n",
      "    output = self.conn.send(event=h11.EndOfMessage())\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 512, in send\n",
      "    data_list = self.send_with_data_passthrough(event)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_connection.py\", line 545, in send_with_data_passthrough\n",
      "    writer(event, data_list.append)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 67, in __call__\n",
      "    self.send_eom(event.headers, write)\n",
      "  File \"c:\\Users\\16148\\anaconda3\\envs\\dev\\lib\\site-packages\\h11\\_writers.py\", line 96, in send_eom\n",
      "    raise LocalProtocolError(\"Too little data for declared Content-Length\")\n",
      "h11._util.LocalProtocolError: Too little data for declared Content-Length\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.008 to 1.000\n",
      "Max probability at index: 12\n",
      "Corresponds to label: mannerism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 1\n",
      "Corresponds to label: american_realism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 1\n",
      "Corresponds to label: american_realism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 23\n",
      "Corresponds to label: surrealism\n",
      "Processed image shape: (256, 256, 3)\n",
      "Value range: 0.000 to 1.000\n",
      "Max probability at index: 3\n",
      "Corresponds to label: art_informel\n"
     ]
    }
   ],
   "source": [
    "import gradio as gr\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "from typing import Dict\n",
    "import os\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "def preprocess_image(image):\n",
    "    try:\n",
    "        if isinstance(image, str):\n",
    "            img = Image.open(image)\n",
    "        elif isinstance(image, np.ndarray):\n",
    "            # BGR to RGB if from numpy/Gradio\n",
    "            image = image[..., ::-1]\n",
    "            img = Image.fromarray(image)\n",
    "        else:\n",
    "            return None, \"Unsupported image format\"\n",
    "            \n",
    "        # Always convert to RGB\n",
    "        if img.mode != 'RGB':\n",
    "            img = img.convert('RGB')\n",
    "            \n",
    "        # Resize first\n",
    "        target_size = 256\n",
    "        w, h = img.size\n",
    "        ratio = min(target_size / w, target_size / h)\n",
    "        new_w = int(w * ratio)\n",
    "        new_h = int(h * ratio)\n",
    "        resized = img.resize((new_w, new_h), Image.LANCZOS)\n",
    "        \n",
    "        # Calculate mean color from resized image\n",
    "        resized_array = np.array(resized)\n",
    "        mean_color = tuple(map(int, np.mean(resized_array, axis=(0, 1))))\n",
    "        \n",
    "        # Create padded image\n",
    "        new_image = Image.new('RGB', (target_size, target_size), mean_color)\n",
    "        \n",
    "        # Calculate padding\n",
    "        x_offset = (target_size - new_w) // 2\n",
    "        y_offset = (target_size - new_h) // 2\n",
    "        \n",
    "        # Paste the resized image\n",
    "        new_image.paste(resized, (x_offset, y_offset))\n",
    "        \n",
    "        # Convert to numpy and normalize\n",
    "        final_array = np.array(new_image, dtype=np.float32) / 255.0\n",
    "        \n",
    "        return final_array, None\n",
    "            \n",
    "    except Exception as e:\n",
    "        return None, f\"Error processing image: {str(e)}\"\n",
    "\n",
    "\n",
    "class ArtStyleClassifier:\n",
    "    def __init__(self, model_path: str = \"art_classifier_curated.keras\"):\n",
    "        self.cnn_model = self._load_cnn_model(model_path)\n",
    "        styles = [\n",
    "            'naive_art', 'baroque', 'rococo', 'romanticism', 'art_deco',\n",
    "            'american_realism', 'art_nouveau', 'expressionism', 'modernism',\n",
    "            'post_impressionism', 'high_renaissance', 'cubism',\n",
    "            'abstract_expressionism', 'art_informel', 'mannerism',\n",
    "            'northern_renaissance', 'surrealism', 'symbolism',\n",
    "            'early_renaissance', 'neo_romantic', 'ukiyo_e', 'impressionism',\n",
    "            'pop_art', 'fauvism', 'neoclassicism', 'minimalism'\n",
    "        ]\n",
    "        self.label_encoder = LabelEncoder()\n",
    "        self.label_encoder.fit(styles)\n",
    "        self.style_labels = self.label_encoder.classes_\n",
    "\n",
    "    def _load_cnn_model(self, model_path):\n",
    "        if not os.path.exists(model_path):\n",
    "            raise FileNotFoundError(f\"Model file not found: {model_path}\")\n",
    "        return tf.keras.models.load_model(model_path, compile=False)\n",
    "\n",
    "    def preprocess_image(self, image):\n",
    "        processed_image, error = preprocess_image(image)\n",
    "        if error:\n",
    "            raise Exception(error)\n",
    "        return processed_image\n",
    "\n",
    "    def predict(self, image):\n",
    "        try:\n",
    "            processed_image = self.preprocess_image(image)\n",
    "            print(f\"Processed image shape: {processed_image.shape}\")\n",
    "            print(f\"Value range: {processed_image.min():.3f} to {processed_image.max():.3f}\")\n",
    "            \n",
    "            # Check order consistency\n",
    "            predictions = self.analyze_image(processed_image)\n",
    "            probs_array = list(predictions.values())\n",
    "            print(f\"Max probability at index: {np.argmax(probs_array)}\")\n",
    "            print(f\"Corresponds to label: {self.style_labels[np.argmax(probs_array)]}\")\n",
    "                \n",
    "            # Sort predictions by probability\n",
    "            sorted_predictions = sorted(predictions.items(), key=lambda x: x[1], reverse=True)\n",
    "            \n",
    "            # Format output\n",
    "            output_text = \"Top 5 Predictions:\\n\\n\"\n",
    "            for style, prob in sorted_predictions[:5]:\n",
    "                output_text += f\"{style}: {prob:.1%}\\n\"\n",
    "            \n",
    "            return output_text\n",
    "        except Exception as e:\n",
    "            return f\"Error: {str(e)}\"\n",
    "\n",
    "    def analyze_image(self, image) -> Dict[str, float]:\n",
    "        if len(image.shape) == 3:\n",
    "            image = np.expand_dims(image, 0)\n",
    "        \n",
    "        probabilities = self.cnn_model.predict(image, verbose=0)[0]\n",
    "        return {style: float(prob) for style, prob in zip(self.style_labels, probabilities)}\n",
    "\n",
    "# Initialize the classifier\n",
    "classifier = ArtStyleClassifier()\n",
    "\n",
    "# Create Gradio interface\n",
    "iface = gr.Interface(\n",
    "    fn=classifier.predict,\n",
    "    inputs=gr.Image(type=\"numpy\"),\n",
    "    outputs=gr.Textbox(label=\"Predictions\"),\n",
    "    title=\"Art Style Classifier\",\n",
    "    description=\"Upload an artwork to classify its artistic style\",\n",
    "    \n",
    ")\n",
    "\n",
    "# Launch the interface\n",
    "if __name__ == \"__main__\":\n",
    "    iface.launch()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "dev",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
